### PR TITLE
Kano wifi gui

### PR DESCRIPTION
**Pull request by skarbat**

### CODE REVIEW

**Comment by alex5imon** [comment]
@skarbat @carolineclark kano-wifi-gui needs to live in `kano-settings` rather than toolset.

**Comment by alex5imon** [comment]
@skarbat this PR needs to be moved to `settings` rather than `toolset`

**Comment by pazdera** [comment]
Should we do something about this?

**Comment by alex5imon** [comment]
yeah @pazdera we should close it :)

Thanks!

**Pull request closed without merging**
