### PR TITLE
Fixing classic mode logoff to terminate all user programs

### PR DESCRIPTION
**Pull request by skarbat**
This PR complements: https://github.com/KanoComputing/os-dashboard/pull/361

### CODE REVIEW

**Comment by Ealdwulf** [comment]
@skarbat is this PR out of date?

**Comment by radujipa** [comment]
@Ealdwulf @skarbat I thought we were holding off from merging this

**Comment by skarbat** [comment]
@radujipa @Ealdwulf , not be merged. We replaced logout for reboots on this image, due to the sound problems.

Same with this one: https://github.com/KanoComputing/os-dashboard/pull/361

**Comment by Ealdwulf** [comment]
@skarbat Do you want to close this then?

**Comment by skarbat** [comment]
Yes, @Ealdwulf - Although just a reminder that we'll have to keep an eye when we re-enable the logout button.

**Pull request closed without merging**
