### PR TITLE
Packaging: Split libraries into separate Debian packages

### PR DESCRIPTION
**Pull request by tombettany**
Make `libkano_networking` separately installable. Also add python
helper libraries.

cc @pazdera @Ealdwulf @convolu

### CODE REVIEW

**Comment by alex5imon** [comment]
@tombettany what is the status of this PR? Is this just for debugging or something you would like to include in 3.1.0?

**Comment by pazdera** [comment]
Packaging-wise this looks really good! 👍

**Comment by convolu** [comment]
:shipit:

**Comment by tombettany** [comment]
Merging for testing.

**Pull request merged**
