### PR TITLE
Adding background updates to network hook

### PR DESCRIPTION
**Pull request by skarbat**
Needed by this PR: https://github.com/KanoComputing/os-dashboard/pull/249

### CODE REVIEW

**Comment by skarbat** [comment]
@Ealdwulf @radujipa could you have a quick look? needed by the advised updates

**Comment by Ealdwulf** [comment]
Makes sense. Are we going to remove the old call to the updater here: https://github.com/KanoComputing/kano-desktop/blob/b32d814009ee77f928c0b2eb1f01b8be743feb8a/kdesk/icon-hooks.sh#L116

**Comment by skarbat** [comment]
I thought about that too @Ealdwulf , I don't think it hurts.

**Comment by radujipa** [comment]
Looks good to me :shipit:

**Comment by skarbat** [comment]
Thanks guys - merging now.

**Pull request merged**
