### PR TITLE
Utils: Separate into submodules

### PR DESCRIPTION
**Pull request by tombettany**
Split utility functions into several files rather than one very large
(and ever-expanding) file. Import all the functions with `util`'s
`__init__.py` to provide backwards compatibility.

Thoughts @convolu @Ealdwulf?

### CODE REVIEW

**Comment by Ealdwulf** [comment]
Really neat @tombettany :+1:

**Comment by convolu** [comment]
long overdue. :shipit: 

It may be worth informing everyone once this is merged just in case we start getting weird issues.
cc @KanoComputing/software-team

**Comment by tombettany** [comment]
Should this actually be merged to `jessie` rather than `master`?

**Comment by convolu** [comment]
I would go for `jessie` to keep it consistent

**Pull request closed without merging**
