### PR TITLE
Configure the correct audio output channel based on settings

### PR DESCRIPTION
**Pull request by radujipa**
The play_sound function was playing audio with omxplayer on both
HDMI and Jack. This meant that the library controlling the PiHat
LEDs was getting desynchronised and lost control over it. This
change sets the output channel based on what is set.

### CODE REVIEW

**Comment by radujipa** [comment]
[(P1) Make Art - Sounds in challenges destabilise the PiHat library causing the lights to flash erratically](https://trello.com/c/OSyMedVS/1090-p1-make-art-sounds-in-challenges-destabilise-the-pihat-library-causing-the-lights-to-flash-erratically)

**Comment by radujipa** [comment]
@skarbat @tombettany Merging this for QA to test on a clean rc tomorrow. Please still review.

**Comment by skarbat** [comment]
Looks good @radujipa 

Do you think kdesk can misbehave for the same situations?

 * https://github.com/KanoComputing/kdesk/blob/master/src/sound.cpp#L53

**Comment by radujipa** [comment]
@skarbat That's a good question! I'll check again, but I haven't seen it causing issues on the desktop

**Pull request merged**
