### PR TITLE
Fixes for unit tests:

### PR DESCRIPTION
**Pull request by Ealdwulf**
This PR:
 Adds an API call to set log dir for test purposes, uses it in the test.
 Changes to actual returned code for compute module.
@skarbat @tombettany

### CODE REVIEW

**Comment by skarbat** [comment]
Is it not possible to override the environment variable from the test modules instead?
Otherwise looks good @Ealdwulf

**Comment by Ealdwulf** [comment]
What environment variable, @skarbat ?

**Comment by skarbat** [comment]
Sorry @Ealdwulf , I mean to say, here:

 * https://github.com/KanoComputing/kano-toolset/blob/67b1df7b6ac5bfa63fd3a44fa6246df75bc9f7f0/kano/_logging.py#L45

if it could do something like `os.getenv('USER_LOGS_DIR')` then you wouldn't need to insert a test function in the core logging library, is it?

**Comment by Ealdwulf** [comment]
I just had a go at using an environment variable instead, but it would be a more invasive change, because at the moment USER_LOGS_DIR is a global, but the tests assume you can change it after initialisation. We've have to look at the environment variable everywhere USER_LOGS_DIR is used, not just at init time. Or move it, and other functions,  into the Logger Class. I'd rather not do that right now.

**Comment by skarbat** [comment]
Oh... never mind @Ealdwulf - let's go 👍

**Comment by Ealdwulf** [comment]
Thanks for the thinking anyway @skarbat :-)

**Pull request merged**
