### PR TITLE
Volume jessie fix

### PR DESCRIPTION
**Pull request by rluz**
Control Master volume only for Jessie, no need for PCM control as
Chromium does not require jackd for audio.

@alex5imon @convolu

### CODE REVIEW

**Comment by alex5imon** [comment]
how does this affect non-jessie users? @rluz

**Comment by convolu** [comment]
@rluz You may want to rebase the jessie branch on top of master and then cherry pick your commit over a new branch because if we merge this PR we will have an unnecessarily complicated history.

@alex5imon This is a Jessie-only change

**Comment by pazdera** [comment]
Rebased here: https://github.com/KanoComputing/kano-toolset/pull/153

**Comment by rluz** [comment]
@alex5imon it doesn't affect wheezy user because they will still have pcm linked to master volume and midori for youtube and jessie users will have only Master volume and chromium for youtube

**Pull request closed without merging**
