### PR TITLE
Adding the new cpuid tracker to the network hook

### PR DESCRIPTION
**Pull request by pazdera**
Depends on: https://github.com/KanoComputing/kano-profile/pull/329

### CODE REVIEW

**Comment by pazdera** [comment]
Sorry guys, I forgot to tag you, @alex5imon and @skarbat.

**Comment by skarbat** [comment]
looks great @pazdera . I can't see the dependency towards kano-profile, so perhaps would be good to embrace this task in an exception block, and pass on failure, so the rest of the code proceeds?

**Comment by pazdera** [comment]
That's a good idea. I'll put it in an additional try.

The reason while we don't have the dependency there is because it would be
circular. Profile depends on toolset :-/.



On Monday, 28 September 2015, Albert Casals <notifications@github.com>
wrote:

> looks great @pazdera <https://github.com/pazdera> . I can't see the
> dependency towards kano-profile, so perhaps would be good to embrace this
> task in an exception block, and pass on failure, so the rest of the code
> proceeds?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/KanoComputing/kano-toolset/pull/150#issuecomment-143775962>
> .
>


-- 
Radek Pazdera
Software Engineer at Kano <http://www.kano.me>

**Comment by pazdera** [comment]
@skarbat Fixed, thanks!

**Comment by skarbat** [comment]
great one @pazdera Radek!

**Comment by pazdera** [comment]
Cheers, @skarbat! I'll merge this.

**Pull request merged**
